### PR TITLE
FastLM // + \n to the end of LM data if not exist.

### PR DESCRIPTION
**Pull request by ShikiSuen**
Addressing: https://github.com/openvanilla/McBopomofo/issues/215

### CODE REVIEW

**Comment by zonble** [comment]
The parser for user phrases has been moved to another language model. We have no need to modify FastLM.

**Comment by zonble** [comment]
See https://github.com/zonble/McBopomofo/commit/5d0d4dd360b6e7efc0afb1b6525fccb97c89b957

**Comment by ShikiSuen** [comment]
@zonble 我剛剛看到了您有在 LanguageModelManager.mm 裡面補上。感謝提醒。

**Comment by zonble** [comment]
Actually the probability information is also dropped but the parser is compatible with legacy data.txt format. The new format looks like

```
小麥注音 ㄒㄧㄠˇ-ㄇㄞˋ-ㄓㄨˋ-ㄧㄣ
小麥注音 ㄒㄧㄠˇ-ㄇㄞˋ-ㄓㄨˋ-ㄧㄣ Anything after the end of the input keys would be dropped but the line is still valid.
```

**Comment by ShikiSuen** [comment]
@zonble It looks nice.
I wonder whether it supports parsing Hanyu Pinyin to Zhuyin.
When loading the user dictionary, it automatically parses HanyuPinyin in the file and replace them to Zhuyin.

I have an SED file that can do this, FYI. MIT-NoTradeMark License.
[SEDUtils-HYPY2BPMF.zip](https://github.com/zonble/McBopomofo/files/7855197/SEDUtils-HYPY2BPMF.zip)

Or maybe the Formosa module can do this.

**Comment by zonble** [comment]
BTW, modifying a file in a function/method called "open" is not a good practice. Anyone who call the function cannot image that the function would do anything other than merely open and read the file. We call such hidden behaviors "side effects", and side effects is the root of most of the bugs.

**Pull request closed without merging**
